### PR TITLE
Added a no italic, no bold alternative

### PR DESCRIPTION
**Pull request by blakewatson**
I use Operator Mono and even though it has beautiful italics I just don’t care for font style or font weight formatting in code. I thought I would add an alternative for your consideration. All styles are identical except for all bold and italics have been removed.

Screen Shot 2021-01-22 at 9 29 21 PM

### CODE REVIEW

**Comment by bdielman** [comment]
@blakewatson - Hi Blake! Thanks for the PR! We recently migrated this theme over to the Dracula Theme org so I want to make sure that any changes stick to the spec. Currently looking into how we should handle variants for official themes. In the meantime feel free to use your fork for now and be sure to keep it updated with any changes in this repo as the colors may change as I bring more of the styles in line with the spec.

**Comment by blakewatson** [comment]
@bdielman Sounds good. Rather than have an alternate theme, my preference would be to have an editor setting that could disable bold/italics globally. I saw some discussion where VS Code might be implementing something like that.

**Comment by bdielman** [comment]
That would be the ideal solution. 😄

**Comment by bdielman** [comment]
@blakewatson - Sorry for the delayed response. I'm going to close this PR for now. I want to keep this as close to the spec as possible. I agree with the idea that disabling of italics/bold should happen at the editor level so I'll be bringing that up in the Nova developer forum.

**Pull request closed without merging**
